### ISSUE TITLE
Feature: Add functions to checkout and checkin the asset

### ISSUE THREAD

**Issue by ashokkumarta** [ashokkumarta/dampy#4]
Make the functionalities for checkout and checkin of assets to the feature set

**Comment by TotallyNotChase** [comment]
Hello, I'd like to take it on, can you elaborate what do you mean by this though?
What should be added and to which file exactly?

**Comment by ashokkumarta** [comment]
Thanks for the interest. You would need AEM (Adobe Experience Manager a commercial product) 6.1 or above to work on this tool. This tool is essentially a python wrapper to work on the Assets feature of AEM. 
 
AEM has the feature to checkout and checkin the assets, typically to be checked out before editing an asset and checked in post the edits. Have attached the screenshot of this feature for reference
![checkin](https://user-images.githubusercontent.com/5450267/66304333-903f4d80-e91a-11e9-9764-5b9cfaa9e0d6.PNG)
![checkout](https://user-images.githubusercontent.com/5450267/66304335-903f4d80-e91a-11e9-8bfe-c8a4bb8cb20b.PNG)

The code for handling the features of Assets in in the file dampy/lib/Assets.py. Each function in this file handles a specific feature. We will have to add two new functions to it 
checkout()
checkin()

and implement the checkout and checkin functionalities here which is essentially to call the AEM webservice which handles the checkout and checkin functionality with appropriate parameters

**Comment by ashokkumarta** [comment]
Check-in / check-out feature merged to master
